# Notes:
# See infra/ansible/ufw-solana/roles/ufw-solana/tasks/bm_setup.yml for an alternative approach for this
- name: Check if PasswordAuthentication is set to yes
  ansible.builtin.shell: grep '^#PasswordAuthentication yes$' /etc/ssh/sshd_config
  register: grep_sshd_config_result
  ignore_errors: true

- name: Check if PasswordAuthentication is set to yes
  ansible.builtin.shell: grep '^PasswordAuthentication yes$' /etc/ssh/sshd_config.d/50-cloud-init.conf
  register: grep_sshd_cloud_init_result
  ignore_errors: true
  become_user: root
  become: true

- name: Replace PasswordAuthentication yes with no
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication yes$'
    line: 'PasswordAuthentication no'
  when: grep_sshd_config_result.rc == 0
  notify: Restart ssh
  become_user: root
  become: true

- name: Replace PasswordAuthentication yes with no
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/50-cloud-init.conf
    regexp: '^PasswordAuthentication yes$'
    line: 'PasswordAuthentication no'
  when: grep_sshd_cloud_init_result.rc == 0
  notify: Restart ssh
  become_user: root
  become: true
