[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# Workaround for BPF stack overflow in Anchor 0.31.x
[build]
sbf = true

[toolchain.sbf]
# Multiple attempts to disable strict BPF stack analysis
options = [
    "--disable-stack-frame-analysis",
    "--skip-stack-check",
    "-C", "opt-level=s"
]

[programs.localnet]
qtrade_executor = "E4uFtpkcE9vPXfULJaCZrJvoiSW9rJ1oqnhmHJMsEErj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
